"""
exporter.py - Export scan results to a Markdown file.
"""
import os
from datetime import datetime

from .hardware import HardwareProfile
from .recommender import Recommendation

USE_CASE_ICONS = {
    "coding": "💻",
    "reasoning": "🧠",
    "chat": "💬",
}


def export_markdown(
    hw: HardwareProfile,
    grouped: dict[str, list[Recommendation]],
    output_path: str = None,
) -> str:
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = f"ollama_scout_{timestamp}.md"

    lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines.append("# 🔭 ollama-scout Report")
    lines.append(f"\n> Generated: {now}\n")

    lines.append("## 🖥 System Hardware\n")
    lines.append("| Component | Details |")
    lines.append("|-----------|---------|")
    lines.append(f"| OS | {hw.os} |")
    lines.append(f"| CPU | {hw.cpu_name} |")
    lines.append(f"| Cores / Threads | {hw.cpu_cores} / {hw.cpu_threads} |")
    lines.append(f"| RAM | {hw.ram_gb} GB |")

    if hw.gpus:
        for i, gpu in enumerate(hw.gpus):
            label = "GPU" if i == 0 else f"GPU {i+1}"
            lines.append(f"| {label} | {gpu.name} ({gpu.vram_gb} GB VRAM) |")
    else:
        lines.append("| GPU | None detected |")

    lines.append("")

    for use_case, recs in grouped.items():
        if not recs:
            continue
        icon = USE_CASE_ICONS.get(use_case, "🤖")
        lines.append(f"## {icon} {use_case.capitalize()} Models\n")
        lines.append("| Model | Tag | Quant | Size | Params | Fit | Mode | Note | Status |")
        lines.append("|-------|-----|-------|------|--------|-----|------|------|--------|")

        for rec in recs:
            status = "✔ Pulled" if rec.model.pulled else "Available"
            lines.append(
                f"| {rec.model.name} "
                f"| {rec.variant.tag} "
                f"| {rec.variant.quantization} "
                f"| {rec.variant.size_gb}GB "
                f"| {rec.variant.param_size} "
                f"| {rec.fit_label} "
                f"| {rec.run_mode} "
                f"| {rec.note} "
                f"| {status} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [ollama-scout](https://github.com/sandy-sp/ollama-scout)_")

    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return os.path.abspath(output_path)
